name: Merge HU con validacion pruebas Unitarias
on:
  push:
    branches: 
      - 'HU**'

permissions:
  contents: write

jobs:

  PalabraClaveCommit:
    if: ${{ contains(github.event.head_commit.message, 'MERGE') }}
    name: palabra
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0

    - name: Pull desde el servidor
      env:
        ramaLocal: ${{ github.ref }}
        USERNAME: ${{ secrets.USERNAME }}
        TOKEN: ${{ secrets.TOKEN }}
    
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: develop
        target_branch: ${{ github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: Merge develop HU

    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
   
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Correr pruebas unitarias
      id: correr-pruebas
      run: python -m unittest -v tests/test_logica_recetario.py

    - name: Pruebas con errores salida
      if: ${{ failure() }}
      run: |
          echo "Error"
          exit 1

    - name: Pruebas sin errores Merge a Develop
      if: ${{ success() }}
      env:
        ramaLocal: ${{ github.ref }}
        USERNAME: ${{ secrets.USERNAME }}
        TOKEN: ${{ secrets.TOKEN }}
    
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: ${{ github.ref }}
        target_branch: develop
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: Merge HU a develop


    - name: Cálculo de cubrimiento
      id: cubrimiento
      run: |
          coverage run -m unittest tests/test_logica_recetario.py
          coverage report -m
